version: 2
jobs:
  build:
    working_directory: /code
    docker:
      - image: tray/sbt:a
      - image: redis:2.8.19
      - image: nats:0.7.2
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Start test databases
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker run -d --name postgres piotrtrzpil/postgres-cs-test
            docker run -d --name cassandra piotrtrzpil/cassandra-cs-test
      - restore_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-cache
      - run:
          name: Initial setup
          command: echo "sbt -v -ivy /ivy -sbt-dir /sbt/dir -sbt-boot /sbt/boot -sbt-launch-dir /sbt/launch \$@" > sbt && chmod 0755 ./sbt

      - run: ./sbt clean test

      - save_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-cache
          paths:
            - /ivy
            - /sbt
      - store_test_results:
          path: target/test-reports

      - run: ./sbt universal:package-zip-tarball

      - run:
          name: Docker build and push
          command: |
            mv target/universal/${CIRCLE_PROJECT_REPONAME}.tgz ${CIRCLE_PROJECT_REPONAME}.tgz
            saneBranchName=$(python /scripts/sane_branch_name.py ${CIRCLE_BRANCH})
            dockerRepoName="piotrtrzpil/${CIRCLE_PROJECT_REPONAME}"

            docker build -t ${dockerRepoName}:${CIRCLE_SHA1} -t ${dockerRepoName}:${saneBranchName} --build-arg GIT_COMMIT=$CIRCLE_SHA1 --build-arg REPO_NAME=$CIRCLE_PROJECT_REPONAME .

            python /scripts/replace_base_image.py "$(cat staging/Dockerfile)" $CIRCLE_SHA1 > staging/DockerfileMod
            python /scripts/replace_base_image.py "$(cat production/Dockerfile)" $CIRCLE_SHA1 > production/DockerfileMod

            docker build -t ${dockerRepoName}:staging-${CIRCLE_SHA1} -t ${dockerRepoName}:staging-${saneBranchName} -f staging/DockerfileMod staging
            docker build -t ${dockerRepoName}:production-${CIRCLE_SHA1} -t ${dockerRepoName}:production-${saneBranchName} -f production/DockerfileMod production

            docker push ${dockerRepoName}:${CIRCLE_SHA1}
            docker push ${dockerRepoName}:staging-${CIRCLE_SHA1}
            docker push ${dockerRepoName}:production-${CIRCLE_SHA1}
            docker push ${dockerRepoName}:${saneBranchName}
            docker push ${dockerRepoName}:staging-${saneBranchName}
            docker push ${dockerRepoName}:production-${saneBranchName}