version: 2
jobs:
  build:
    working_directory: /code
    docker:
      - image: tray/sbt:a
    steps:
      - checkout
      - restore_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-cache
      - run: |
          echo "sbt -v -ivy /ivy -sbt-dir /sbt/dir -sbt-boot /sbt/boot -sbt-launch-dir /sbt/launch \$@" > sbt && chmod 0755 ./sbt
          ./sbt clean test
      - save_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-cache
          paths:
            - /ivy
            - /sbt
      - store_test_results:
          path: target/test-reports
      - run: |
          ./sbt universal:package-zip-tarball
      - setup_docker_engine
      - run: |
          mv target/universal/${CIRCLE_PROJECT_REPONAME}.tgz ${CIRCLE_PROJECT_REPONAME}.tgz
          saneBranchName=$(python /scripts/sane_branch_name.py ${CIRCLE_BRANCH})
          dockerRepoName="piotrtrzpil/${CIRCLE_PROJECT_REPONAME}"
          docker build -t ${dockerRepoName}:${CIRCLE_SHA1} -t ${dockerRepoName}:${saneBranchName} --build-arg GIT_COMMIT=$CIRCLE_SHA1 --build-arg REPO_NAME=$CIRCLE_PROJECT_REPONAME .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ${dockerRepoName}:${CIRCLE_SHA1}
          docker push ${dockerRepoName}:${saneBranchName}