version: 2
jobs:
  build:
    working_directory: /code
    docker:
      - image: tray/sbt
    steps:
      - checkout
      - restore_cache:
          key: test-repo-cache
      - run: |
          sbt -sbt-opts /etc/.sbtopts clean test
      - save_cache:
          key: test-repo-cache
          paths:
            - /ivy
            - /sbt
      - store_test_results:
          path: target/test-reports
      - run: |
          sbt -sbt-opts /etc/.sbtopts universal:package-zip-tarball
      - run: mv target/universal/${CIRCLE_PROJECT_REPONAME}-1.0-SNAPSHOT.tgz ${CIRCLE_PROJECT_REPONAME}.tgz
      - setup_docker_engine
      - run: |
          docker build -t piotrtrzpil/test-repo:circle --build-arg GIT_COMMIT=$CIRCLE_SHA1 .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push piotrtrzpil/test-repo:circle


