version: 2
jobs:
  build:
    working_directory: /code
    docker:
      - image: tray/sbt
    steps:
      - checkout
      - restore_cache:
          key: test-repo-cache

      - run: |
          sbt -v \
              -ivy /ivy \
              -sbt-dir /sbt/dir \
              -sbt-boot /sbt/boot \
              -sbt-launch-dir /sbt/launch \
            clean universal:package-zip-tarball
     # - run: tar -xvzf target/universal/${CIRCLE_PROJECT_REPONAME}-1.0-SNAPSHOT.tgz -C $WERCKER_OUTPUT_DIR/
      - save_cache:
          key: test-repo-cache
          paths:
            - /ivy
            - /sbt
      - run: mv target/universal/${CIRCLE_PROJECT_REPONAME}-1.0-SNAPSHOT.tgz ${CIRCLE_PROJECT_REPONAME}-1.0-SNAPSHOT.tgz
      - setup_docker_engine
      # use a build image that already has Docker (recommended)
      # or install it during a build like we do here
      - run: |
          set -ex
          curl -L -o /tmp/docker-1.12.3.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker-1.12.3.tgz
          mv /tmp/docker/* /usr/bin
      - run: |
          docker build -t piotrtrzpil/test-repo:circle .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push piotrtrzpil/test-repo:circle

